apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: vote-app
  namespace: default
spec:
  serviceAccountName: default
  fetch:
    - git:
        url: https://github.com/rahulrai-in/azure-voting-app-dotnet
        ref: origin/main
        subPath: kubernetes-manifests/
  template:
    - ytt: {}
  deploy:
    - kapp: {}
