apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: vote-app
  namespace: carvel-apps
spec:
  serviceAccountName: infra-provisioner-sa
  fetch:
    - git:
        url: https://github.com/yannicklevederpvtl/vote-app.git
        ref: origin/main
        subPath: kubernetes-manifests/
  template:
    - ytt: {}
  deploy:
    - kapp: {}
